(2025-04-06 15:10:28,246) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-06 15:10:41,106) [INFO] Reloading abletonosc...
(2025-04-06 15:10:41,107) [INFO] Reloaded code
(2025-04-06 15:10:42,768) [WARNING] First1:[]
(2025-04-06 15:10:42,768) [WARNING] First2:[]
(2025-04-06 15:10:42,769) [WARNING] Test1:['Reverb']
(2025-04-06 15:10:49,054) [INFO] Disconnecting...
(2025-04-06 15:10:49,772) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-06 15:10:55,671) [INFO] Reloading abletonosc...
(2025-04-06 15:10:55,673) [INFO] Reloaded code
(2025-04-06 15:10:56,585) [WARNING] First1:[]
(2025-04-06 15:10:56,587) [WARNING] First2:[]
(2025-04-06 15:10:56,587) [WARNING] First2:['Reverb']
(2025-04-06 15:10:56,587) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:11:03,252) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-06 15:11:28,951) [WARNING] First1:[]
(2025-04-06 15:11:28,952) [WARNING] First2:[]
(2025-04-06 15:11:28,952) [WARNING] First2:['Reverb']
(2025-04-06 15:11:28,952) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:11:38,319) [INFO] [<Device.Device object at 0x000000002B5941C0>, <Device.Device object at 0x000000002B594040>, <Device.Device object at 0x000000002B594AC0>]
(2025-04-06 15:14:31,732) [INFO] Reloading abletonosc...
(2025-04-06 15:14:31,733) [INFO] Reloaded code
(2025-04-06 15:14:35,440) [WARNING] First1:[]
(2025-04-06 15:14:35,440) [WARNING] First2:[]
(2025-04-06 15:14:35,440) [WARNING] First2:['Reverb']
(2025-04-06 15:14:35,440) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:14:38,441) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-06 15:14:40,157) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-06 15:14:49,525) [WARNING] First1:[]
(2025-04-06 15:14:49,525) [WARNING] First2:[]
(2025-04-06 15:14:49,525) [WARNING] First2:['Reverb']
(2025-04-06 15:14:49,525) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:14:55,175) [INFO] [<Device.Device object at 0x0000000020167CC0>, <Device.Device object at 0x0000000020167F40>, <Device.Device object at 0x00000000201677C0>]
(2025-04-06 15:15:02,448) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-06 15:15:02,451) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 13, in device_callback
    device = self.song.tracks[track_index].devices[device_index]
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: Index out of range

(2025-04-06 15:15:06,932) [INFO] Getting property for device: name = Filter Delay
(2025-04-06 15:15:14,415) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-06 15:15:14,416) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 13, in device_callback
    device = self.song.tracks[track_index].devices[device_index]
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: Index out of range

(2025-04-06 15:15:17,132) [INFO] Getting property for device: class_name = FilterDelay
(2025-04-06 15:15:19,966) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-06 15:15:19,966) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 13, in device_callback
    device = self.song.tracks[track_index].devices[device_index]
             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
IndexError: Index out of range

(2025-04-06 15:18:30,245) [INFO] Reloading abletonosc...
(2025-04-06 15:18:30,246) [INFO] Reloaded code
(2025-04-06 15:18:31,285) [WARNING] First1:[]
(2025-04-06 15:18:31,285) [WARNING] First2:[]
(2025-04-06 15:18:31,285) [WARNING] First2:['Reverb']
(2025-04-06 15:18:31,285) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:18:53,702) [WARNING] First1:[]
(2025-04-06 15:18:53,702) [WARNING] First2:[]
(2025-04-06 15:18:53,702) [WARNING] First2:['Reverb']
(2025-04-06 15:18:53,702) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:19:07,103) [INFO] [<Device.Device object at 0x000000002B596BC0>, <Device.Device object at 0x000000002B5962C0>, <Device.Device object at 0x000000002B596AC0>]
(2025-04-06 15:19:15,916) [INFO] Getting property for device: name = Reverb
(2025-04-06 15:19:18,899) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 15:19:31,949) [INFO] Getting property for device: type = audio_effect
(2025-04-06 15:20:04,041) [INFO] Reloading abletonosc...
(2025-04-06 15:20:04,043) [INFO] Reloaded code
(2025-04-06 15:20:04,932) [WARNING] First1:[]
(2025-04-06 15:20:04,932) [WARNING] First2:[]
(2025-04-06 15:20:04,932) [WARNING] First2:['Reverb']
(2025-04-06 15:20:04,932) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:21:53,772) [INFO] Reloading abletonosc...
(2025-04-06 15:21:53,774) [INFO] Reloaded code
(2025-04-06 15:21:54,460) [WARNING] First1:[]
(2025-04-06 15:21:54,460) [WARNING] First2:[]
(2025-04-06 15:21:54,460) [WARNING] First2:['Reverb']
(2025-04-06 15:21:54,460) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:24:16,507) [INFO] Reloading abletonosc...
(2025-04-06 15:24:16,508) [INFO] Reloaded code
(2025-04-06 15:24:17,263) [WARNING] First1:[]
(2025-04-06 15:24:17,263) [WARNING] First2:[]
(2025-04-06 15:24:17,263) [WARNING] First2:['Reverb']
(2025-04-06 15:24:17,263) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 15:28:02,582) [INFO] Reloading abletonosc...
(2025-04-06 15:28:02,584) [INFO] Reloaded code
(2025-04-06 15:31:48,294) [INFO] Reloading abletonosc...
(2025-04-06 15:31:48,295) [INFO] Reloaded code
(2025-04-06 15:32:44,925) [INFO] Reloading abletonosc...
(2025-04-06 15:32:44,928) [INFO] Reloaded code
(2025-04-06 15:33:56,078) [INFO] Reloading abletonosc...
(2025-04-06 15:33:56,079) [INFO] Reloaded code
(2025-04-06 15:34:04,421) [INFO] Reloading abletonosc...
(2025-04-06 15:34:04,422) [INFO] Reloaded code
(2025-04-06 15:34:28,620) [INFO] Reloading abletonosc...
(2025-04-06 15:34:28,622) [INFO] Reloaded code
(2025-04-06 15:38:20,004) [INFO] Reloading abletonosc...
(2025-04-06 15:38:20,006) [INFO] Reloaded code
(2025-04-06 16:31:47,701) [INFO] Reloading abletonosc...
(2025-04-06 16:31:47,702) [INFO] Reloaded code
(2025-04-06 16:32:29,739) [INFO] Reloading abletonosc...
(2025-04-06 16:32:29,740) [INFO] Reloaded code
(2025-04-06 16:32:36,695) [WARNING] First1:[]
(2025-04-06 16:32:36,695) [WARNING] First2:[]
(2025-04-06 16:32:36,695) [WARNING] First2:['Reverb']
(2025-04-06 16:32:36,695) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 16:33:09,164) [INFO] Reloading abletonosc...
(2025-04-06 16:33:09,166) [INFO] Reloaded code
(2025-04-06 16:33:20,213) [INFO] Reloading abletonosc...
(2025-04-06 16:33:20,215) [INFO] Reloaded code
(2025-04-06 16:33:21,805) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 16:33:21,806) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 139, in return_track_devices_class_name
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-06 16:33:30,320) [INFO] [<Device.Device object at 0x000000000E7013C0>, <Device.Device object at 0x000000000E701540>, <Device.Device object at 0x000000000E701240>]
(2025-04-06 16:34:01,514) [INFO] Reloading abletonosc...
(2025-04-06 16:34:01,516) [INFO] Reloaded code
(2025-04-06 16:34:08,071) [INFO] [<Device.Device object at 0x000000000E8D3C40>, <Device.Device object at 0x000000000E8D3BC0>, <Device.Device object at 0x000000000E8D3B40>]
(2025-04-06 16:35:01,984) [INFO] Reloading abletonosc...
(2025-04-06 16:35:01,986) [INFO] Reloaded code
(2025-04-06 16:35:17,121) [INFO] Reloading abletonosc...
(2025-04-06 16:35:17,123) [INFO] Reloaded code
(2025-04-06 16:36:04,446) [INFO] Reloading abletonosc...
(2025-04-06 16:36:04,447) [INFO] Reloaded code
(2025-04-06 16:36:09,472) [INFO] Reloading abletonosc...
(2025-04-06 16:36:09,474) [INFO] Reloaded code
(2025-04-06 16:37:39,882) [INFO] Reloading abletonosc...
(2025-04-06 16:37:39,884) [INFO] Reloaded code
(2025-04-06 16:37:47,088) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:38:36,356) [INFO] Reloading abletonosc...
(2025-04-06 16:38:36,357) [INFO] Reloaded code
(2025-04-06 16:38:37,478) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:47:18,506) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:55:18,132) [INFO] Reloading abletonosc...
(2025-04-06 16:55:18,138) [INFO] Reloaded code
(2025-04-06 16:55:18,764) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:56:40,887) [INFO] Reloading abletonosc...
(2025-04-06 16:56:40,888) [INFO] Reloaded code
(2025-04-06 16:56:41,692) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:59:37,549) [INFO] Reloading abletonosc...
(2025-04-06 16:59:37,550) [INFO] Reloaded code
(2025-04-06 16:59:38,304) [INFO] Getting property for device: name = Reverb
(2025-04-06 16:59:55,565) [INFO] Reloading abletonosc...
(2025-04-06 16:59:55,568) [INFO] Reloaded code
(2025-04-06 17:00:05,678) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:05:31,870) [INFO] Reloading abletonosc...
(2025-04-06 17:05:31,872) [INFO] Reloaded code
(2025-04-06 17:05:32,578) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:05:53,463) [INFO] Reloading abletonosc...
(2025-04-06 17:05:53,464) [INFO] Reloaded code
(2025-04-06 17:05:54,275) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:06:05,986) [INFO] Reloading abletonosc...
(2025-04-06 17:06:05,987) [INFO] Reloaded code
(2025-04-06 17:06:06,608) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:07:41,804) [INFO] Reloading abletonosc...
(2025-04-06 17:07:41,805) [INFO] Reloaded code
(2025-04-06 17:07:42,810) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:10:30,401) [INFO] Reloading abletonosc...
(2025-04-06 17:10:30,403) [INFO] Reloaded code
(2025-04-06 17:10:31,292) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:11:21,048) [INFO] Reloading abletonosc...
(2025-04-06 17:11:21,049) [INFO] Reloaded code
(2025-04-06 17:11:21,877) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:14:05,263) [INFO] Reloading abletonosc...
(2025-04-06 17:14:05,264) [INFO] Reloaded code
(2025-04-06 17:14:11,852) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:16:48,078) [INFO] Reloading abletonosc...
(2025-04-06 17:16:48,080) [INFO] Reloaded code
(2025-04-06 17:16:48,786) [WARNING] DEBUG: track_callback called with params: [6, 0]
(2025-04-06 17:16:48,786) [WARNING] DEBUG: Processing track_index: 6
(2025-04-06 17:16:48,786) [WARNING] DEBUG: rv from func for track_index 6: (0, 'Reverb')
(2025-04-06 17:16:48,786) [WARNING] DEBUG about to return: ("(6, 0, 'Reverb')",)
(2025-04-06 17:22:15,347) [INFO] Reloading abletonosc...
(2025-04-06 17:22:15,349) [INFO] Reloaded code
(2025-04-06 17:22:16,271) [INFO] Logs:[(<Track.Track object at 0x000000003B2F65C0>, <Track.Track object at 0x000000003B2F6540>, <Track.Track object at 0x000000003B2F64C0>, <Track.Track object at 0x000000003B2F6440>, <Track.Track object at 0x000000003B2F63C0>, <Track.Track object at 0x000000003B2F6340>, <Track.Track object at 0x000000003B2F6240>, <Track.Track object at 0x000000003B2F61C0>, <Track.Track object at 0x00000000007156C0>)]
(2025-04-06 17:25:01,229) [INFO] Reloading abletonosc...
(2025-04-06 17:25:01,230) [INFO] Reloaded code
(2025-04-06 17:25:01,818) [INFO] Logs:[(<Track.Track object at 0x000000003B2ABE40>, <Track.Track object at 0x000000003B2ABEC0>, <Track.Track object at 0x000000003B2ABF40>, <Track.Track object at 0x000000003B2AB9C0>, <Track.Track object at 0x000000003B2A8040>, <Track.Track object at 0x000000003B2AB940>, <Track.Track object at 0x000000003B2A83C0>, <Track.Track object at 0x000000003B2F5740>, <Track.Track object at 0x000000000E765A40>)]
(2025-04-06 17:25:01,818) [ERROR] AbletonOSC: Error handling OSC message: 'Track' object has no attribute 'index'
(2025-04-06 17:25:01,819) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 401, in device_get_name
    return (f"({track.index}, {device_index}, '{device_name}')",)
                ^^^^^^^^^^^
AttributeError: 'Track' object has no attribute 'index'

(2025-04-06 17:25:13,343) [INFO] Reloading abletonosc...
(2025-04-06 17:25:13,345) [INFO] Reloaded code
(2025-04-06 17:25:13,950) [INFO] Logs:[(<Track.Track object at 0x000000003B2DF5C0>, <Track.Track object at 0x000000003B2DF540>, <Track.Track object at 0x000000003B2DF4C0>, <Track.Track object at 0x000000003B2DF440>, <Track.Track object at 0x000000003B2DF3C0>, <Track.Track object at 0x000000003B2DF340>, <Track.Track object at 0x000000003B2DF240>, <Track.Track object at 0x000000003B2DF1C0>, <Track.Track object at 0x000000003B2DF640>)]
(2025-04-06 17:26:50,884) [INFO] Reloading abletonosc...
(2025-04-06 17:26:50,885) [INFO] Reloaded code
(2025-04-06 17:26:51,673) [INFO] Logs:[(<Track.Track object at 0x000000003B2F5040>, <Track.Track object at 0x000000003B2F50C0>, <Track.Track object at 0x000000003B2F5140>, <Track.Track object at 0x000000003B2F51C0>, <Track.Track object at 0x000000003B2F5240>, <Track.Track object at 0x000000003B2F52C0>, <Track.Track object at 0x000000003B2F5440>, <Track.Track object at 0x000000003B2F53C0>, <Track.Track object at 0x0000000000689AC0>)]
(2025-04-06 17:27:03,600) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:28:01,275) [INFO] Reloading abletonosc...
(2025-04-06 17:28:01,277) [INFO] Reloaded code
(2025-04-06 17:28:02,216) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:28:02,216) [ERROR] AbletonOSC: Error handling OSC message: str() argument 'encoding' must be str, not int
(2025-04-06 17:28:02,217) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 65, in device_callback
    return (str(track_index, device_index, *rv),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: str() argument 'encoding' must be str, not int

(2025-04-06 17:28:36,848) [INFO] Reloading abletonosc...
(2025-04-06 17:28:36,849) [INFO] Reloaded code
(2025-04-06 17:28:37,574) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:30:52,476) [INFO] Reloading abletonosc...
(2025-04-06 17:30:52,477) [INFO] Reloaded code
(2025-04-06 17:30:53,201) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:30:58,736) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:31:12,409) [INFO] Reloading abletonosc...
(2025-04-06 17:31:12,411) [INFO] Reloaded code
(2025-04-06 17:31:13,134) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:31:40,693) [INFO] Reloading abletonosc...
(2025-04-06 17:31:40,694) [INFO] Reloaded code
(2025-04-06 17:31:41,701) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:33:27,504) [INFO] Reloading abletonosc...
(2025-04-06 17:33:27,506) [INFO] Reloaded code
(2025-04-06 17:33:28,279) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:34:18,998) [INFO] Reloading abletonosc...
(2025-04-06 17:34:18,999) [INFO] Reloaded code
(2025-04-06 17:34:19,940) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:35:33,210) [INFO] Reloading abletonosc...
(2025-04-06 17:35:33,213) [INFO] Reloaded code
(2025-04-06 17:35:33,834) [INFO] Getting property for device: type = audio_effect
(2025-04-06 17:36:41,073) [INFO] Reloading abletonosc...
(2025-04-06 17:36:41,075) [INFO] Reloaded code
(2025-04-06 17:36:42,101) [INFO] Getting property for device: type = 2
(2025-04-06 17:37:09,436) [INFO] Logs:[(<Track.Track object at 0x000000003B413BC0>, <Track.Track object at 0x000000003B412F40>, <Track.Track object at 0x000000003B413140>, <Track.Track object at 0x000000003B412640>, <Track.Track object at 0x000000003B410A40>, <Track.Track object at 0x000000003B399640>, <Track.Track object at 0x000000003B39AE40>, <Track.Track object at 0x000000003B399440>, <Track.Track object at 0x000000003B3BD840>)]
(2025-04-06 17:37:28,669) [INFO] Logs:[(<Track.Track object at 0x000000003B410A40>, <Track.Track object at 0x000000003B39B6C0>, <Track.Track object at 0x000000003B399440>, <Track.Track object at 0x000000003B39AE40>, <Track.Track object at 0x000000003B39BBC0>, <Track.Track object at 0x000000003B399640>, <Track.Track object at 0x000000003B3BFEC0>, <Track.Track object at 0x000000003B3BE240>, <Track.Track object at 0x000000003B412640>)]
(2025-04-06 17:37:31,004) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:37:38,711) [INFO] Reloading abletonosc...
(2025-04-06 17:37:38,712) [INFO] Reloaded code
(2025-04-06 17:37:39,852) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:45:35,258) [INFO] Reloading abletonosc...
(2025-04-06 17:45:35,260) [INFO] Reloaded code
(2025-04-06 17:45:35,980) [INFO] Logs:[(<Track.Track object at 0x000000003B5151C0>, <Track.Track object at 0x000000003B517CC0>, <Track.Track object at 0x000000003B517C40>, <Track.Track object at 0x000000003B517BC0>, <Track.Track object at 0x000000003B517B40>, <Track.Track object at 0x000000003B517AC0>, <Track.Track object at 0x000000003B5179C0>, <Track.Track object at 0x000000003B517940>, <Track.Track object at 0x000000003B498B40>)]
(2025-04-06 17:45:49,810) [INFO] Reloading abletonosc...
(2025-04-06 17:45:49,811) [INFO] Reloaded code
(2025-04-06 17:45:50,617) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:45:50,617) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 15, in track_callback
    if params[0] == "*":
       ~~~~~~^^^
IndexError: list index out of range

(2025-04-06 17:45:54,250) [INFO] Logs:[(<Track.Track object at 0x000000003B5628C0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5627C0>, <Track.Track object at 0x000000003B562740>, <Track.Track object at 0x000000003B5626C0>, <Track.Track object at 0x000000003B562640>, <Track.Track object at 0x000000003B562540>, <Track.Track object at 0x000000003B5624C0>, <Track.Track object at 0x000000000E7015C0>)]
(2025-04-06 17:46:06,594) [INFO] Reloading abletonosc...
(2025-04-06 17:46:06,595) [INFO] Reloaded code
(2025-04-06 17:46:07,349) [INFO] Logs:[(<Track.Track object at 0x000000003B5165C0>, <Track.Track object at 0x000000003B516540>, <Track.Track object at 0x000000003B5164C0>, <Track.Track object at 0x000000003B516440>, <Track.Track object at 0x000000003B5163C0>, <Track.Track object at 0x000000003B516340>, <Track.Track object at 0x000000003B5162C0>, <Track.Track object at 0x000000003B5161C0>, <Track.Track object at 0x000000000E7667C0>)]
(2025-04-06 17:47:57,587) [INFO] Reloading abletonosc...
(2025-04-06 17:47:57,588) [INFO] Reloaded code
(2025-04-06 17:48:06,460) [INFO] Logs:[(<Track.Track object at 0x000000003B5AB740>, <Track.Track object at 0x000000003B5AB4C0>, <Track.Track object at 0x000000003B5AB540>, <Track.Track object at 0x000000003B5AB340>, <Track.Track object at 0x000000003B5AB2C0>, <Track.Track object at 0x000000003B5AB1C0>, <Track.Track object at 0x000000003B5AB7C0>, <Track.Track object at 0x000000003B5AB6C0>, <Track.Track object at 0x000000003B5AB840>)]
(2025-04-06 17:48:09,593) [INFO] Logs:[(<Track.Track object at 0x000000003B5AB7C0>, <Track.Track object at 0x000000003B5AB740>, <Track.Track object at 0x000000003B5AB840>, <Track.Track object at 0x000000003B5AB640>, <Track.Track object at 0x000000003B5AB6C0>, <Track.Track object at 0x000000003B5AB240>, <Track.Track object at 0x000000003B5AB2C0>, <Track.Track object at 0x000000003B5AB4C0>, <Track.Track object at 0x000000003B5AB1C0>)]
(2025-04-06 17:48:12,043) [INFO] Logs:[(<Track.Track object at 0x000000003B5AB2C0>, <Track.Track object at 0x000000003B5AB7C0>, <Track.Track object at 0x000000003B5AB1C0>, <Track.Track object at 0x000000003B5AB140>, <Track.Track object at 0x000000003B5AB4C0>, <Track.Track object at 0x000000003B5AB540>, <Track.Track object at 0x000000003B5AB6C0>, <Track.Track object at 0x000000003B5AB740>, <Track.Track object at 0x000000003B5AB240>)]
(2025-04-06 17:48:23,104) [INFO] Reloading abletonosc...
(2025-04-06 17:48:23,105) [INFO] Reloaded code
(2025-04-06 17:48:23,793) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:29,193) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:29,194) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:48:29,195) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 323, in track_get_device_is_grouped
    if(str(type(full_data[_[0]].canonical_parent)) == "<class 'Chain.Chain'>"):#hasattr(full_data[_[0]].canonical_parent, 'chains')):
                ~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:48:30,760) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:32,225) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:34,843) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:34,844) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-06 17:48:34,844) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 331, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-06 17:48:36,309) [INFO] Logs:[(<Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:48:47,161) [INFO] Logs:[(<Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:48,542) [INFO] Logs:[(<Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:52,462) [INFO] Logs:[(<Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:48:52,463) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:48:52,463) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 357, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:48:53,339) [INFO] Logs:[(<Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:48:53,340) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:48:53,340) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 357, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:49:05,506) [WARNING] First1:[]
(2025-04-06 17:49:05,507) [WARNING] First2:[]
(2025-04-06 17:49:05,507) [WARNING] First2:['Reverb']
(2025-04-06 17:49:05,507) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 17:49:06,122) [WARNING] First1:[]
(2025-04-06 17:49:06,122) [WARNING] First2:[]
(2025-04-06 17:49:06,122) [WARNING] First2:['Reverb']
(2025-04-06 17:49:06,122) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 17:49:06,440) [INFO] [<Device.Device object at 0x000000003B561AC0>, <Device.Device object at 0x000000003B562840>, <Device.Device object at 0x000000003B560F40>]
(2025-04-06 17:49:06,855) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:49:06,954) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:49:07,055) [INFO] Getting property for device: type = 2
(2025-04-06 17:49:07,922) [INFO] Logs:[(<Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:49:08,221) [INFO] Logs:[(<Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:49:08,321) [INFO] Logs:[(<Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:49:08,538) [INFO] Logs:[(<Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5161C0>, <Track.Track object at 0x000000003B560340>)]
(2025-04-06 17:49:08,538) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:49:08,539) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 323, in track_get_device_is_grouped
    if(str(type(full_data[_[0]].canonical_parent)) == "<class 'Chain.Chain'>"):#hasattr(full_data[_[0]].canonical_parent, 'chains')):
                ~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:49:08,638) [INFO] Logs:[(<Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:49:08,638) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-06 17:49:08,639) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 331, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-06 17:49:08,955) [INFO] Logs:[(<Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:49:09,054) [INFO] Logs:[(<Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:49:09,055) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:49:09,055) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 357, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:50:03,467) [WARNING] First1:[]
(2025-04-06 17:50:03,468) [WARNING] First2:[]
(2025-04-06 17:50:03,468) [WARNING] First2:['Reverb']
(2025-04-06 17:50:03,468) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 17:50:04,100) [WARNING] First1:[]
(2025-04-06 17:50:04,100) [WARNING] First2:[]
(2025-04-06 17:50:04,101) [WARNING] First2:['Reverb']
(2025-04-06 17:50:04,101) [WARNING] Test1:['Reverb', 'Gate']
(2025-04-06 17:50:04,416) [INFO] [<Device.Device object at 0x000000003B560F40>, <Device.Device object at 0x000000003B561AC0>, <Device.Device object at 0x000000003B5601C0>]
(2025-04-06 17:50:04,834) [INFO] Getting property for device: name = Reverb
(2025-04-06 17:50:04,934) [INFO] Getting property for device: class_name = Reverb
(2025-04-06 17:50:05,049) [INFO] Getting property for device: type = 2
(2025-04-06 17:50:05,851) [INFO] Logs:[(<Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5161C0>)]
(2025-04-06 17:50:06,166) [INFO] Logs:[(<Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:50:06,283) [INFO] Logs:[(<Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:50:06,500) [INFO] Logs:[(<Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B5161C0>, <Track.Track object at 0x000000003B5606C0>)]
(2025-04-06 17:50:06,500) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-06 17:50:06,501) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 323, in track_get_device_is_grouped
    if(str(type(full_data[_[0]].canonical_parent)) == "<class 'Chain.Chain'>"):#hasattr(full_data[_[0]].canonical_parent, 'chains')):
                ~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-06 17:50:06,600) [INFO] Logs:[(<Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:50:06,817) [INFO] Logs:[(<Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B560140>, <Track.Track object at 0x000000003B561040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5606C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:50:47,533) [INFO] Logs:[(<Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B5602C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B560340>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:50:47,533) [ERROR] AbletonOSC: Error handling OSC message: list indices must be integers or slices, not str
(2025-04-06 17:50:47,534) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 26, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 357, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
TypeError: list indices must be integers or slices, not str

(2025-04-06 17:50:48,916) [INFO] Logs:[(<Track.Track object at 0x000000003B560F40>, <Track.Track object at 0x000000003B561AC0>, <Track.Track object at 0x000000003B5601C0>, <Track.Track object at 0x000000003B560040>, <Track.Track object at 0x000000003B560740>, <Track.Track object at 0x000000003B562840>, <Track.Track object at 0x000000003B5618C0>, <Track.Track object at 0x000000003B5600C0>, <Track.Track object at 0x000000003B515740>)]
(2025-04-06 17:52:25,729) [INFO] Disconnecting...
(2025-04-08 21:08:35,325) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-08 21:08:38,371) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-08 21:08:38,457) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-08 21:08:48,328) [INFO] Disconnecting...
(2025-04-08 21:08:49,048) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-08 21:08:49,455) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-08 21:08:49,555) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-08 21:09:07,464) [INFO] Reloading abletonosc...
(2025-04-08 21:09:07,466) [INFO] Reloaded code
(2025-04-08 21:09:24,050) [INFO] Reloading abletonosc...
(2025-04-08 21:09:24,052) [INFO] Reloaded code
(2025-04-08 21:11:43,715) [INFO] Reloading abletonosc...
(2025-04-08 21:11:43,737) [INFO] Reloaded code
(2025-04-08 21:12:44,297) [INFO] Reloading abletonosc...
(2025-04-08 21:12:44,299) [INFO] Reloaded code
(2025-04-08 21:16:24,430) [INFO] Disconnecting...
(2025-04-11 21:11:10,116) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-11 21:11:13,251) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-11 21:11:13,335) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-11 21:12:52,896) [INFO] Reloading abletonosc...
(2025-04-11 21:12:52,898) [INFO] Reloaded code
(2025-04-12 03:54:16,439) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-12 03:54:19,664) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 03:54:19,785) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 03:56:27,084) [INFO] Reloading abletonosc...
(2025-04-12 03:56:27,085) [INFO] Reloaded code
(2025-04-12 04:01:37,361) [INFO] Reloading abletonosc...
(2025-04-12 04:01:37,362) [INFO] Reloaded code
(2025-04-12 04:03:54,241) [INFO] Reloading abletonosc...
(2025-04-12 04:03:54,242) [INFO] Reloaded code
(2025-04-12 04:03:54,243) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:03:54,352) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:04:03,108) [INFO] Reloading abletonosc...
(2025-04-12 04:04:03,109) [INFO] Reloaded code
(2025-04-12 04:04:03,109) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:04:03,219) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:16:19,946) [INFO] Reloading abletonosc...
(2025-04-12 04:16:19,947) [INFO] Reloaded code
(2025-04-12 04:16:19,948) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:16:20,042) [WARNING] AbletonOSC: Non-fatal socket error: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 158, in process
    data, remote_addr = self._socket.recvfrom(65536)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

(2025-04-12 04:18:04,791) [INFO] Reloading abletonosc...
(2025-04-12 04:18:04,792) [INFO] Reloaded code
(2025-04-12 04:19:56,667) [INFO] Reloading abletonosc...
(2025-04-12 04:19:56,669) [INFO] Reloaded code
(2025-04-12 04:22:29,587) [INFO] Reloading abletonosc...
(2025-04-12 04:22:29,588) [INFO] Reloaded code
(2025-04-12 04:22:30,382) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-12 04:22:33,182) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-12 04:22:34,548) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-12 04:22:35,465) [ERROR] AbletonOSC: Unknown OSC address: /live/song/get/return_track_names
(2025-04-12 04:24:00,578) [INFO] Reloading abletonosc...
(2025-04-12 04:24:00,579) [INFO] Reloaded code
(2025-04-12 04:24:01,305) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate tuple (not "Vector") to tuple
(2025-04-12 04:24:01,315) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + [self.song.master_track] + self.song.return_tracks).index(self.song.view.selected_track),)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate tuple (not "Vector") to tuple

(2025-04-12 04:24:08,995) [INFO] Reloading abletonosc...
(2025-04-12 04:24:08,997) [INFO] Reloaded code
(2025-04-12 04:24:13,955) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate tuple (not "list") to tuple
(2025-04-12 04:24:13,956) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + [self.song.master_track] + [self.song.return_tracks]).index(self.song.view.selected_track),)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate tuple (not "list") to tuple

(2025-04-12 04:25:13,307) [INFO] Reloading abletonosc...
(2025-04-12 04:25:13,309) [INFO] Reloaded code
(2025-04-12 04:25:15,433) [ERROR] AbletonOSC: Error handling OSC message: 'Track' object has no attribute '__iter__'
(2025-04-12 04:25:15,435) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + self.song.master_track + self.song.return_tracks).index(self.song.view.selected_track),)
                 ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
AttributeError: 'Track' object has no attribute '__iter__'

(2025-04-12 04:25:27,990) [INFO] Reloading abletonosc...
(2025-04-12 04:25:27,991) [INFO] Reloaded code
(2025-04-12 04:25:28,833) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate tuple (not "Vector") to tuple
(2025-04-12 04:25:28,833) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + [self.song.master_track] + self.song.return_tracks).index(self.song.view.selected_track),)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate tuple (not "Vector") to tuple

(2025-04-12 04:25:51,323) [INFO] Reloading abletonosc...
(2025-04-12 04:25:51,324) [INFO] Reloaded code
(2025-04-12 04:25:53,334) [ERROR] AbletonOSC: Error handling OSC message: 'Track' object is not iterable
(2025-04-12 04:25:53,334) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + tuple(self.song.master_track) + self.song.return_tracks).index(self.song.view.selected_track),)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Track' object is not iterable

(2025-04-12 04:26:02,656) [INFO] Reloading abletonosc...
(2025-04-12 04:26:02,657) [INFO] Reloaded code
(2025-04-12 04:26:03,698) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate tuple (not "Vector") to tuple
(2025-04-12 04:26:03,700) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 15, in get_selected_track
    return (list(self.song.tracks + tuple([self.song.master_track]) + self.song.return_tracks).index(self.song.view.selected_track),)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate tuple (not "Vector") to tuple

(2025-04-12 04:27:07,152) [INFO] Reloading abletonosc...
(2025-04-12 04:27:07,153) [INFO] Reloaded code
(2025-04-12 04:29:45,099) [INFO] Reloading abletonosc...
(2025-04-12 04:29:45,101) [INFO] Reloaded code
(2025-04-12 04:31:03,876) [INFO] Reloading abletonosc...
(2025-04-12 04:31:03,878) [INFO] Reloaded code
(2025-04-12 04:31:10,769) [WARNING] <Track.Track object at 0x000000000E7869C0>...<Base.Vector object at 0x000000000E7869C0>
(2025-04-12 04:31:34,960) [INFO] Reloading abletonosc...
(2025-04-12 04:31:34,961) [INFO] Reloaded code
(2025-04-12 04:31:36,002) [WARNING] <Track.Track object at 0x00000000226C5540>...[<Track.Track object at 0x000000000E7C8BC0>, <Track.Track object at 0x000000000E7CA3C0>]
(2025-04-12 04:32:30,928) [INFO] Reloading abletonosc...
(2025-04-12 04:32:30,930) [INFO] Reloaded code
(2025-04-12 04:32:31,554) [WARNING] <Track.Track object at 0x000000000E7CB4C0>...[<Track.Track object at 0x000000000E7C8BC0>, <Track.Track object at 0x00000000162C4EC0>]
(2025-04-12 04:32:31,554) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate list (not "Track") to list
(2025-04-12 04:32:31,555) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + self.song.master_track].extend(list(self.song.return_tracks)).index(self.song.view.selected_track),)
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "Track") to list

(2025-04-12 04:32:46,360) [INFO] Reloading abletonosc...
(2025-04-12 04:32:46,362) [INFO] Reloaded code
(2025-04-12 04:32:50,721) [WARNING] <Track.Track object at 0x000000000E7866C0>...[<Track.Track object at 0x00000000162C5B40>, <Track.Track object at 0x00000000162C7340>]
(2025-04-12 04:32:50,721) [ERROR] AbletonOSC: Error handling OSC message: can only concatenate list (not "Track") to list
(2025-04-12 04:32:50,722) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + self.song.master_track + list(self.song.return_tracks)].index(self.song.view.selected_track),)
             ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "Track") to list

(2025-04-12 04:33:04,402) [INFO] Reloading abletonosc...
(2025-04-12 04:33:04,404) [INFO] Reloaded code
(2025-04-12 04:33:05,796) [WARNING] <Track.Track object at 0x00000000162C5CC0>...[<Track.Track object at 0x0000000016304340>, <Track.Track object at 0x0000000016305B40>]
(2025-04-12 04:33:05,796) [ERROR] AbletonOSC: Error handling OSC message: <Track.Track object at 0x00000000163059C0> is not in list
(2025-04-12 04:33:05,796) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + [self.song.master_track] + list(self.song.return_tracks)].index(self.song.view.selected_track),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: <Track.Track object at 0x00000000163059C0> is not in list

(2025-04-12 04:33:22,013) [WARNING] <Track.Track object at 0x00000000162C5CC0>...[<Track.Track object at 0x00000000163059C0>, <Track.Track object at 0x0000000016305AC0>]
(2025-04-12 04:33:22,013) [ERROR] AbletonOSC: Error handling OSC message: <Track.Track object at 0x0000000016305940> is not in list
(2025-04-12 04:33:22,014) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + [self.song.master_track] + list(self.song.return_tracks)].index(self.song.view.selected_track),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: <Track.Track object at 0x0000000016305940> is not in list

(2025-04-12 04:33:26,795) [WARNING] <Track.Track object at 0x00000000226C54C0>...[<Track.Track object at 0x0000000016305940>, <Track.Track object at 0x0000000016305B40>]
(2025-04-12 04:33:26,796) [ERROR] AbletonOSC: Error handling OSC message: <Track.Track object at 0x00000000163052C0> is not in list
(2025-04-12 04:33:26,796) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + [self.song.master_track] + list(self.song.return_tracks)].index(self.song.view.selected_track),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: <Track.Track object at 0x00000000163052C0> is not in list

(2025-04-12 04:33:43,770) [INFO] Reloading abletonosc...
(2025-04-12 04:33:43,771) [INFO] Reloaded code
(2025-04-12 04:33:44,579) [WARNING] [[<Track.Track object at 0x0000000016306AC0>, <Track.Track object at 0x0000000016306FC0>, <Track.Track object at 0x0000000016306CC0>, <Track.Track object at 0x000000001634C6C0>, <Track.Track object at 0x00000000226C54C0>, <Track.Track object at 0x000000001634C4C0>, <Track.Track object at 0x000000001634C440>]]
(2025-04-12 04:33:44,580) [ERROR] AbletonOSC: Error handling OSC message: <Track.Track object at 0x000000001634C4C0> is not in list
(2025-04-12 04:33:44,580) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\view.py", line 16, in get_selected_track
    return ([list(self.song.tracks) + [self.song.master_track] + list(self.song.return_tracks)].index(self.song.view.selected_track),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: <Track.Track object at 0x000000001634C4C0> is not in list

(2025-04-12 04:34:24,755) [INFO] Reloading abletonosc...
(2025-04-12 04:34:24,781) [INFO] Reloaded code
(2025-04-12 04:34:29,631) [WARNING] [[<Track.Track object at 0x00000000226C7540>, <Track.Track object at 0x00000000226C74C0>, <Track.Track object at 0x00000000226C7A40>, <Track.Track object at 0x00000000226C6F40>, <Track.Track object at 0x00000000226C7840>, <Track.Track object at 0x00000000226C7B40>, <Track.Track object at 0x00000000226C7AC0>]]
(2025-04-12 04:34:34,814) [WARNING] [[<Track.Track object at 0x00000000226C7740>, <Track.Track object at 0x00000000226C7840>, <Track.Track object at 0x00000000226C7540>, <Track.Track object at 0x00000000226C7640>, <Track.Track object at 0x00000000226C6F40>, <Track.Track object at 0x00000000226C74C0>, <Track.Track object at 0x00000000226C77C0>]]
(2025-04-12 04:34:37,015) [WARNING] [[<Track.Track object at 0x00000000226C7640>, <Track.Track object at 0x00000000226C7B40>, <Track.Track object at 0x00000000226C6F40>, <Track.Track object at 0x00000000226C7740>, <Track.Track object at 0x00000000226C5D40>, <Track.Track object at 0x00000000226C7CC0>, <Track.Track object at 0x00000000226C7840>]]
(2025-04-12 04:34:39,197) [WARNING] [[<Track.Track object at 0x00000000226C7540>, <Track.Track object at 0x00000000226C74C0>, <Track.Track object at 0x00000000226C5D40>, <Track.Track object at 0x00000000226C7CC0>, <Track.Track object at 0x00000000226C7A40>, <Track.Track object at 0x00000000226C77C0>, <Track.Track object at 0x00000000226C7AC0>]]
(2025-04-12 04:34:44,148) [WARNING] [[<Track.Track object at 0x00000000226C6F40>, <Track.Track object at 0x00000000226C7A40>, <Track.Track object at 0x00000000226C77C0>, <Track.Track object at 0x00000000226C7540>, <Track.Track object at 0x00000000226C7AC0>, <Track.Track object at 0x00000000226C7640>, <Track.Track object at 0x00000000226C74C0>]]
(2025-04-12 04:34:46,398) [WARNING] [[<Track.Track object at 0x00000000226C5D40>, <Track.Track object at 0x00000000226C7AC0>, <Track.Track object at 0x00000000226C7640>, <Track.Track object at 0x00000000226C6F40>, <Track.Track object at 0x00000000226C74C0>, <Track.Track object at 0x00000000226C7740>, <Track.Track object at 0x00000000226C7A40>]]
(2025-04-12 04:34:48,882) [WARNING] [[<Track.Track object at 0x00000000226C77C0>, <Track.Track object at 0x00000000226C74C0>, <Track.Track object at 0x00000000226C7740>, <Track.Track object at 0x00000000226C5D40>, <Track.Track object at 0x00000000226C7A40>, <Track.Track object at 0x00000000226C7CC0>, <Track.Track object at 0x00000000226C7AC0>]]
(2025-04-12 04:34:50,914) [WARNING] [[<Track.Track object at 0x00000000226C7640>, <Track.Track object at 0x00000000226C7A40>, <Track.Track object at 0x00000000226C7CC0>, <Track.Track object at 0x00000000226C77C0>, <Track.Track object at 0x00000000226C7AC0>, <Track.Track object at 0x00000000226C7540>, <Track.Track object at 0x00000000226C74C0>]]
(2025-04-12 04:35:37,865) [INFO] Reloading abletonosc...
(2025-04-12 04:35:37,867) [INFO] Reloaded code
(2025-04-12 04:35:47,727) [WARNING] [[<Track.Track object at 0x00000000226C77C0>, <Track.Track object at 0x000000001634FBC0>, <Track.Track object at 0x000000001634FB40>, <Track.Track object at 0x000000001634FAC0>, <Track.Track object at 0x00000000226C50C0>, <Track.Track object at 0x000000001634F9C0>, <Track.Track object at 0x000000001634F940>]]
(2025-04-12 04:35:50,976) [WARNING] [[<Track.Track object at 0x00000000226C7740>, <Track.Track object at 0x000000001634FA40>, <Track.Track object at 0x000000001634FBC0>, <Track.Track object at 0x000000001634FB40>, <Track.Track object at 0x00000000226C55C0>, <Track.Track object at 0x000000001634F9C0>, <Track.Track object at 0x000000001634F940>]]
(2025-04-12 04:44:30,895) [INFO] Reloading abletonosc...
(2025-04-12 04:44:30,897) [INFO] Reloaded code
(2025-04-12 04:44:31,638) [WARNING] (6,)
(2025-04-12 04:51:41,657) [INFO] Reloading abletonosc...
(2025-04-12 04:51:41,658) [INFO] Reloaded code
(2025-04-12 04:53:51,689) [INFO] Reloading abletonosc...
(2025-04-12 04:53:51,691) [INFO] Reloaded code
(2025-04-12 05:00:22,765) [WARNING] First1:[]
(2025-04-12 05:00:22,765) [WARNING] First2:[]
(2025-04-12 05:00:22,765) [WARNING] Test1:['Reverb']
(2025-04-12 05:03:30,418) [INFO] Reloading abletonosc...
(2025-04-12 05:03:30,419) [INFO] Reloaded code
(2025-04-12 05:03:30,923) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:03:30,924) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 94, in return_track_color_index
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:03:33,222) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:03:33,224) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:03:34,590) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:03:34,591) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:03:35,624) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-12 05:03:35,624) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 95, in return_track_color_index
    color_index = self.song.return_tracks[track_id].color_index
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: Index out of range

(2025-04-12 05:03:36,390) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-12 05:03:36,391) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 95, in return_track_color_index
    color_index = self.song.return_tracks[track_id].color_index
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: Index out of range

(2025-04-12 05:03:37,656) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-12 05:03:37,657) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 95, in return_track_color_index
    color_index = self.song.return_tracks[track_id].color_index
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: Index out of range

(2025-04-12 05:03:38,406) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-12 05:03:38,407) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 95, in return_track_color_index
    color_index = self.song.return_tracks[track_id].color_index
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: Index out of range

(2025-04-12 05:03:39,439) [ERROR] AbletonOSC: Error handling OSC message: Index out of range
(2025-04-12 05:03:39,440) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 95, in return_track_color_index
    color_index = self.song.return_tracks[track_id].color_index
                  ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
IndexError: Index out of range

(2025-04-12 05:04:00,184) [INFO] Reloading abletonosc...
(2025-04-12 05:04:00,185) [INFO] Reloaded code
(2025-04-12 05:04:01,123) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:04:01,124) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 94, in return_track_color_index
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:04:28,302) [INFO] Reloading abletonosc...
(2025-04-12 05:04:28,333) [INFO] Reloaded code
(2025-04-12 05:04:29,439) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:04:29,440) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 94, in return_track_color_index
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:04:40,202) [INFO] Reloading abletonosc...
(2025-04-12 05:04:40,204) [INFO] Reloaded code
(2025-04-12 05:04:41,973) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:04:41,974) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:04:49,051) [INFO] Reloading abletonosc...
(2025-04-12 05:04:49,052) [INFO] Reloaded code
(2025-04-12 05:05:16,987) [INFO] Reloading abletonosc...
(2025-04-12 05:05:16,989) [INFO] Reloaded code
(2025-04-12 05:05:18,244) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:05:18,245) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:05:25,187) [INFO] Reloading abletonosc...
(2025-04-12 05:05:25,189) [INFO] Reloaded code
(2025-04-12 05:05:26,111) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:05:26,112) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 115, in return_track_devices_type
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:06:20,924) [INFO] Reloading abletonosc...
(2025-04-12 05:06:20,925) [INFO] Reloaded code
(2025-04-12 05:06:36,440) [INFO] Reloading abletonosc...
(2025-04-12 05:06:36,442) [INFO] Reloaded code
(2025-04-12 05:06:48,474) [INFO] Reloading abletonosc...
(2025-04-12 05:06:48,475) [INFO] Reloaded code
(2025-04-12 05:06:51,064) [INFO] []
(2025-04-12 05:07:17,216) [INFO] Disconnecting...
(2025-04-12 05:07:18,127) [INFO] Started AbletonOSC on address ('0.0.0.0', 11000)
(2025-04-12 05:07:22,324) [INFO] Reloading abletonosc...
(2025-04-12 05:07:22,325) [INFO] Reloaded code
(2025-04-12 05:07:23,029) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:07:23,030) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:07:26,955) [INFO] Reloading abletonosc...
(2025-04-12 05:07:26,957) [INFO] Reloaded code
(2025-04-12 05:07:37,972) [INFO] Reloading abletonosc...
(2025-04-12 05:07:37,972) [INFO] Reloaded code
(2025-04-12 05:07:46,772) [INFO] Reloading abletonosc...
(2025-04-12 05:07:46,774) [INFO] Reloaded code
(2025-04-12 05:07:52,400) [INFO] Reloading abletonosc...
(2025-04-12 05:07:52,400) [INFO] Reloaded code
(2025-04-12 05:07:53,611) [INFO] Logs:[(<Track.Track object at 0x000000001D9CD0C0>, <Track.Track object at 0x000000001D9CCE40>, <Track.Track object at 0x000000001D9CCCC0>, <Track.Track object at 0x000000001D9CCB40>, <Track.Track object at 0x000000001D9BE2C0>, <Track.Track object at 0x000000001D9BE140>, <Track.Track object at 0x000000001D9BDA40>, <Track.Track object at 0x000000001D9BD9C0>, <Track.Track object at 0x000000001D9CCEC0>)]
(2025-04-12 05:08:01,289) [INFO] Reloading abletonosc...
(2025-04-12 05:08:01,291) [INFO] Reloaded code
(2025-04-12 05:08:02,212) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:08:02,212) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 15, in track_callback
    if params[0] == "*":
       ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:08:04,012) [INFO] Logs:[(<Track.Track object at 0x000000001D8453C0>, <Track.Track object at 0x000000004B33AF40>, <Track.Track object at 0x000000004B33AEC0>, <Track.Track object at 0x000000004B33ADC0>, <Track.Track object at 0x000000004B33AD40>, <Track.Track object at 0x000000004B33ACC0>, <Track.Track object at 0x000000004B33ABC0>, <Track.Track object at 0x000000004B33AB40>, <Track.Track object at 0x000000001D8455C0>)]
(2025-04-12 05:10:27,276) [INFO] Reloading abletonosc...
(2025-04-12 05:10:27,277) [INFO] Reloaded code
(2025-04-12 05:11:20,948) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:11:20,949) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:11:24,651) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:11:24,653) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:12:17,057) [INFO] Reloading abletonosc...
(2025-04-12 05:12:17,059) [INFO] Reloaded code
(2025-04-12 05:12:17,660) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:12:17,661) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 99, in return_track_devices_name
    track_id = params[0]
               ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:15:33,494) [INFO] Reloading abletonosc...
(2025-04-12 05:15:33,496) [INFO] Reloaded code
(2025-04-12 05:15:34,103) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:15:34,103) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:15:35,786) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:15:35,786) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:15:38,410) [INFO] Reloading abletonosc...
(2025-04-12 05:15:38,411) [INFO] Reloaded code
(2025-04-12 05:15:39,687) [ERROR] AbletonOSC: Error handling OSC message: not enough values to unpack (expected 2, got 1)
(2025-04-12 05:15:39,687) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\song.py", line 108, in song_get_return_track_names
    track_index_min, track_index_max = params
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

(2025-04-12 05:16:20,497) [INFO] Reloading abletonosc...
(2025-04-12 05:16:20,527) [INFO] Reloaded code
(2025-04-12 05:17:26,914) [INFO] Reloading abletonosc...
(2025-04-12 05:17:26,916) [INFO] Reloaded code
(2025-04-12 05:17:50,638) [INFO] [<Device.Device object at 0x000000001D9007C0>, <Device.Device object at 0x000000001D902640>, <Device.Device object at 0x000000001D9016C0>]
(2025-04-12 05:17:59,989) [INFO] Getting property for device: name = Reverb
(2025-04-12 05:20:14,843) [INFO] Reloading abletonosc...
(2025-04-12 05:20:14,844) [INFO] Reloaded code
(2025-04-12 05:20:15,685) [INFO] Getting property for device: name = Reverb
(2025-04-12 05:20:15,685) [ERROR] AbletonOSC: Error handling OSC message: Infered arg_value type is not supported
(2025-04-12 05:20:15,686) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 96, in process_message
    self.send(address=message.address,
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 77, in send
    msg_builder.add_arg(param)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 87, in add_arg
    arg_type = self._get_arg_type(arg_value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\pythonosc\osc_message_builder.py", line 128, in _get_arg_type
    raise ValueError('Infered arg_value type is not supported')
ValueError: Infered arg_value type is not supported

(2025-04-12 05:20:19,476) [INFO] Reloading abletonosc...
(2025-04-12 05:20:19,478) [INFO] Reloaded code
(2025-04-12 05:20:20,218) [INFO] Getting property for device: name = Reverb
(2025-04-12 05:20:35,787) [INFO] Getting property for device: class_name = Reverb
(2025-04-12 05:20:39,521) [INFO] Getting property for device: type = 2
(2025-04-12 05:21:45,737) [INFO] Reloading abletonosc...
(2025-04-12 05:21:45,738) [INFO] Reloaded code
(2025-04-12 05:21:57,421) [INFO] Reloading abletonosc...
(2025-04-12 05:21:57,422) [INFO] Reloaded code
(2025-04-12 05:22:16,294) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-12 05:22:16,295) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 314, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-12 05:23:06,164) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-12 05:23:06,165) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 314, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-12 05:23:24,732) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:23:24,732) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 340, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-12 05:27:39,483) [INFO] Reloading abletonosc...
(2025-04-12 05:27:39,484) [INFO] Reloaded code
(2025-04-12 05:28:06,036) [INFO] Reloading abletonosc...
(2025-04-12 05:28:06,037) [INFO] Reloaded code
(2025-04-12 05:28:14,350) [INFO] Reloading abletonosc...
(2025-04-12 05:28:14,351) [INFO] Reloaded code
(2025-04-12 05:28:57,053) [INFO] Reloading abletonosc...
(2025-04-12 05:28:57,055) [INFO] Reloaded code
(2025-04-12 05:29:25,620) [INFO] Reloading abletonosc...
(2025-04-12 05:29:25,621) [INFO] Reloaded code
(2025-04-12 05:29:39,753) [INFO] Reloading abletonosc...
(2025-04-12 05:29:39,756) [INFO] Reloaded code
(2025-04-12 05:30:54,162) [INFO] Reloading abletonosc...
(2025-04-12 05:30:54,163) [INFO] Reloaded code
(2025-04-12 05:31:36,988) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:31:36,989) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 15, in track_callback
    if params[0] == "*":
       ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:31:43,534) [INFO] Reloading abletonosc...
(2025-04-12 05:31:43,562) [INFO] Reloaded code
(2025-04-12 05:33:38,113) [INFO] Reloading abletonosc...
(2025-04-12 05:33:38,114) [INFO] Reloaded code
(2025-04-12 05:33:39,235) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:33:39,236) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 345, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:33:40,951) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:33:40,953) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 345, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:33:45,318) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:33:45,319) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 345, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
IndexError: list index out of range

(2025-04-12 05:33:47,403) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:33:47,403) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 345, in track_get_device_name_of_chain
    return tuple([_[0],[x.name for x in full_data if str(type(x)) == "<class 'RackDevice.RackDevice'>"][_[0]]])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:35:48,466) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:35:48,466) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 15, in track_callback
    if params[0] == "*":
       ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:35:49,750) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:35:49,750) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 297, in track_get_device_is_foldable
    return tuple([_[0], full_data[_[0]].can_have_chains])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:35:51,033) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:35:51,034) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 297, in track_get_device_is_foldable
    return tuple([_[0], full_data[_[0]].can_have_chains])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:36:03,733) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-12 05:36:03,734) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-12 05:36:05,433) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:36:05,433) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:36:06,999) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:36:07,001) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:36:22,217) [ERROR] AbletonOSC: Error handling OSC message: 'Device' object has no attribute 'chains'
(2025-04-12 05:36:22,217) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                            ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Device' object has no attribute 'chains'

(2025-04-12 05:36:23,850) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:36:23,850) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:36:24,883) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:36:24,883) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 319, in track_get_device_num_of_chains
    return tuple([_[0], len(full_data[_[0]].chains)])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:36:53,299) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:36:53,299) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 55, in device_callback
    track_index, device_index = int(params[0]), int(params[1])
                                    ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:36:57,750) [ERROR] AbletonOSC: Error handling OSC message: list index out of range
(2025-04-12 05:36:57,750) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\device.py", line 55, in device_callback
    track_index, device_index = int(params[0]), int(params[1])
                                                    ~~~~~~^^^
IndexError: list index out of range

(2025-04-12 05:37:07,716) [ERROR] AbletonOSC: Unknown OSC address: /live/device/get/names_of_chains/live/device/get/names_of_devices_in_chain
(2025-04-12 05:37:08,516) [ERROR] AbletonOSC: Error handling OSC message: tuple index out of range
(2025-04-12 05:37:08,517) [WARNING] AbletonOSC: Traceback (most recent call last):
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 166, in process
    self.parse_bundle(data, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 144, in parse_bundle
    self.process_message(message, remote_addr)
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\osc_server.py", line 90, in process_message
    rv = callback(message.params)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 25, in track_callback
    rv = func(track, *args, tuple(params[1:]))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Viktor\Desktop\temp\Ableton\Resources\MIDI Remote Scripts\AbletonOSC\abletonosc\track.py", line 340, in track_get_device_name_of_devicechains
    return tuple([_[0], [x.name for x in full_data[_[0]:] if 'Device.Device' in (str(type(x))) and 'Chain' in str(type(x.canonical_parent))]])
                  ~^^^
IndexError: tuple index out of range

(2025-04-12 05:37:17,772) [INFO] [<Device.Device object at 0x00000000007688C0>, <Device.Device object at 0x0000000000768C40>, <Device.Device object at 0x0000000000769F40>]
